// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "main.h"
#include "clsAppContext.h"
#include <FL/x.h>

static void cb_Extract(Fl_Double_Window*, clsAppContext* v) {
  if (Fl::event()==FL_SHORTCUT && Fl::event_key()==FL_Escape)
    return;
v->cbClose();
}

static void cb_Save(Fl_Button*, clsAppContext* v) {
  v->cbSaveCnf();
}

static void cb_Close(Fl_Button*, clsAppContext* v) {
  v->cbClose();
}

static clsMetaDataTable *MetaDataTable=(clsMetaDataTable *)0;

static void cb_MetaDataTable(clsMetaDataTable*, void*) {
  MetaDataTable->tbl_callback();
}

static void cb_Add(Fl_Button*, clsMetaDataTable* v) {
  v->cbAddRow();
}

static void cb_Del(Fl_Button*, clsMetaDataTable* v) {
  v->cbDelRow();
}

static void cb_Clear(Fl_Button*, clsMetaDataTable* v) {
  v->cbClearAll();
}

static void cb_Cell(Fl_Choice* o, clsAppContext* v) {
  v->cbSelectArea(o->value());
}

static void cb_Text(Fl_ButtonOutput*, clsAppContext* v) {
  v->cbImport();
}

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  clsAppContext AppContext;
  Fl::scheme("gtk+");
  { Fl_Double_Window* o = new Fl_Double_Window(900, 558, "Extract  EIS data from text");
    w = o; if (w) {/* empty */}
    o->callback((Fl_Callback*)cb_Extract, (void*)(&AppContext));
    o->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Input* o = new Fl_Input(390, 430, 100, 25, "Hidden input for paste:");
      o->user_data((void*)(&AppContext));
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      o->hide();
      o->deactivate();
      AppContext.RegisterWg("intx_test",o);
    } // Fl_Input* o
    { Fl_Button* o = new Fl_Button(685, 5, 100, 25, "Save");
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelcolor((Fl_Color)4);
      o->callback((Fl_Callback*)cb_Save, (void*)(&AppContext));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(790, 5, 100, 25, "Close");
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelcolor((Fl_Color)80);
      o->callback((Fl_Callback*)cb_Close, (void*)(&AppContext));
    } // Fl_Button* o
    { clsMetaDataTable* o = MetaDataTable = new clsMetaDataTable(35, 235, 850, 310, "Meta Data");
      MetaDataTable->box(FL_THIN_DOWN_FRAME);
      MetaDataTable->color(FL_BACKGROUND_COLOR);
      MetaDataTable->selection_color(FL_BACKGROUND_COLOR);
      MetaDataTable->labeltype(FL_NORMAL_LABEL);
      MetaDataTable->labelfont(0);
      MetaDataTable->labelsize(18);
      MetaDataTable->labelcolor(FL_FOREGROUND_COLOR);
      MetaDataTable->callback((Fl_Callback*)cb_MetaDataTable, (void*)(&AppContext));
      MetaDataTable->align(Fl_Align(FL_ALIGN_TOP));
      MetaDataTable->when(FL_WHEN_RELEASE);
      AppContext.RegisterWg("tbl_Metadata",o);
      MetaDataTable->end();
    } // clsMetaDataTable* MetaDataTable
    { Fl_Button* o = new Fl_Button(495, 170, 100, 25, "Add row");
      o->callback((Fl_Callback*)cb_Add, (void*)(MetaDataTable));
    } // Fl_Button* o
    { Fl_Value_Input* o = new Fl_Value_Input(345, 110, 100, 30, "Area, cm\302\262:");
      o->labelsize(16);
      o->minimum(0.1);
      o->maximum(1000);
      o->value(16);
      o->textsize(16);
      o->user_data((void*)(&AppContext));
      AppContext.RegisterWg("inpv_Area",o);
      o->color(fl_rgb_color(220,255,255));
    } // Fl_Value_Input* o
    { Fl_Button* o = new Fl_Button(620, 170, 100, 25, "Del row");
      o->callback((Fl_Callback*)cb_Del, (void*)(MetaDataTable));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(735, 170, 100, 25, "Clear All");
      o->callback((Fl_Callback*)cb_Clear, (void*)(MetaDataTable));
    } // Fl_Button* o
    { Fl_Choice* o = new Fl_Choice(90, 114, 160, 26, "Cell type:");
      o->down_box(FL_BORDER_BOX);
      o->labelsize(16);
      o->textsize(16);
      o->callback((Fl_Callback*)cb_Cell, (void*)(&AppContext));
      AppContext.RegisterWg("ch_Area",o);
    } // Fl_Choice* o
    { Fl_ButtonOutput* o = new Fl_ButtonOutput(20, 64, 855, 27, "Text file to import");
      o->box(FL_NO_BOX);
      o->color(FL_DARK_YELLOW);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(16);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->callback((Fl_Callback*)cb_Text, (void*)(&AppContext));
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      o->when(FL_WHEN_RELEASE);
      AppContext.RegisterWg("btout_FOpen",o);
      o->button().label("@fileopen");
      o->button().color(fl_rgb_color(204,230,255));
      o->output().color(fl_rgb_color(204,230,255));
      o->end();
    } // Fl_ButtonOutput* o
    AppContext.Win(o);
    AppContext.init_windows();
    o->end();
  } // Fl_Double_Window* o
  w->icon((const void *)LoadIcon(fl_display, MAKEINTRESOURCE(501)));
  w->show(argc, argv);
  return Fl::run();
}
