// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "form1.h"
#include "clsForm1Context.h"

static void cb_Extract(Fl_Double_Window*, clsForm1Context* v) {
  if (Fl::event()==FL_SHORTCUT && Fl::event_key()==FL_Escape)
    return;
v->cbCancel();
}

static void cb_Cancel(Fl_Button*, clsForm1Context* v) {
  v->cbCancel();
}

static void cb_Next(Fl_Button*, clsForm1Context* v) {
  v->cbtn_frm12Tabl();
}

static void cb_show(Fl_Check_Button* o, clsForm1Context* v) {
  v->cbShowTabs(o->value());
}

static void cb_Next1(Fl_Button*, void* v) {
  ((clsForm1Context *)v)->cbtn_frm12Stat();
}

static void cb_Back(Fl_Button*, clsForm1Context* v) {
  v->cbtn_frm1Back();
}

static void cb_Finish(Fl_Button*, clsForm1Context* v) {
  v->cbFinish();
}

static void cb_Back1(Fl_Button*, void* v) {
  ((clsForm1Context *)v)->cbtn_frm1Back();
}

static void cb_Next2(Fl_Button*, clsForm1Context* v) {
  v->cbWgt2Tab();
}

static void cb_Back2(Fl_Button*, clsForm1Context* v) {
  v->cbtn_frm1Back();
}

static void cb_fileopen(Fl_Button*, clsForm1Context* v) {
  v->cbOpenPrf();
}

static void cb_filesave(Fl_Button*, clsForm1Context* v) {
  v->cbSavePrf();
}

Fl_Double_Window* winit_form1() {
  Fl_Double_Window* w;
  static clsForm1Context Form1Context;
  { Fl_Double_Window* o = new Fl_Double_Window(840, 870, "Extract EIS table");
    w = o; if (w) {/* empty */}
    o->callback((Fl_Callback*)cb_Extract, (void*)(&Form1Context));
    o->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    o->when(FL_WHEN_NEVER);
    { Fl_Button* o = new Fl_Button(690, 25, 100, 25, "Cancel");
      o->callback((Fl_Callback*)cb_Cancel, (void*)(&Form1Context));
      Form1Context.RegisterWg("btn_Close",o);
    } // Fl_Button* o
    { Fl_Tabs* o = new Fl_Tabs(25, 79, 880, 786);
      o->selection_color((Fl_Color)239);
      o->labelsize(18);
      o->user_data((void*)(&Form1Context));
      { Fl_Group* o = new Fl_Group(25, 110, 805, 730, "File");
        o->labelsize(18);
        o->hide();
        { Fl_Multi_Browser1* o = new Fl_Multi_Browser1(36, 225, 779, 615);
          o->box(FL_NO_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(18);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->textfont(4);
          o->user_data((void*)(&Form1Context));
          o->align(Fl_Align(FL_ALIGN_BOTTOM));
          o->when(FL_WHEN_RELEASE_ALWAYS);
          Form1Context.RegisterWg("brw_SLFile",o);
          o->has_scrollbar(2);
        } // Fl_Multi_Browser1* o
        { Fl_Button* o = new Fl_Button(720, 125, 100, 25, "Next");
          o->callback((Fl_Callback*)cb_Next, (void*)(&Form1Context));
          Form1Context.RegisterWg("btn_frm12Tabl",o);
        } // Fl_Button* o
        { Fl_Group* o = new Fl_Group(455, 135, 250, 80, "Separators");
          o->box(FL_GTK_DOWN_FRAME);
          o->labelsize(16);
          { Fl_Choice* o = new Fl_Choice(540, 145, 81, 25, "Columns:");
            o->down_box(FL_BORDER_BOX);
            o->labelsize(16);
            o->textsize(16);
            o->user_data((void*)(&Form1Context));
            Form1Context.RegisterWg("ch_frm1_colsep",o);
          } // Fl_Choice* o
          { Fl_Choice* o = new Fl_Choice(540, 175, 81, 25, "Decimal:");
            o->down_box(FL_BORDER_BOX);
            o->labelsize(16);
            o->textsize(16);
            o->user_data((void*)(&Form1Context));
            Form1Context.RegisterWg("ch_frm1_decsep",o);
          } // Fl_Choice* o
          { Fl_Check_Button* o = new Fl_Check_Button(635, 140, 60, 35, "show\ntabs");
            o->down_box(FL_DOWN_BOX);
            o->callback((Fl_Callback*)cb_show, (void*)(&Form1Context));
            o->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
            Form1Context.RegisterWg("chbtn_ShowTabs",o);
          } // Fl_Check_Button* o
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(230, 135, 220, 80, "Data");
          o->box(FL_GTK_DOWN_FRAME);
          o->labelsize(16);
          { Fl_Value_Output* o = new Fl_Value_Output(280, 180, 75, 30, "Lines:");
            o->labelsize(16);
            o->textsize(16);
            o->user_data((void*)(&Form1Context));
            Form1Context.RegisterWg("vout_frm1_1stLn",o);
          } // Fl_Value_Output* o
          { Fl_Value_Output* o = new Fl_Value_Output(366, 180, 75, 30, ":");
            o->labelsize(16);
            o->textsize(16);
            o->user_data((void*)(&Form1Context));
            Form1Context.RegisterWg("vout_frm1_LastLn",o);
          } // Fl_Value_Output* o
          { Fl_Value_Output* o = new Fl_Value_Output(365, 140, 75, 30, "Header:");
            o->labelsize(16);
            o->textsize(16);
            o->user_data((void*)(&Form1Context));
            Form1Context.RegisterWg("vout_frm1_hdr",o);
          } // Fl_Value_Output* o
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(50, 135, 165, 80, "Metadata");
          o->box(FL_GTK_DOWN_FRAME);
          o->labelsize(16);
          { Fl_Value_Output* o = new Fl_Value_Output(60, 175, 65, 30, "Lines:");
            o->labelsize(16);
            o->minimum(-1);
            o->maximum(100000);
            o->value(-1);
            o->textsize(16);
            o->user_data((void*)(&Form1Context));
            o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            Form1Context.RegisterWg("vout_frm1_Meta1stLn",o);
          } // Fl_Value_Output* o
          { Fl_Value_Output* o = new Fl_Value_Output(135, 175, 65, 30, ":");
            o->labelsize(16);
            o->minimum(1);
            o->maximum(10000);
            o->value(-1);
            o->textsize(16);
            o->user_data((void*)(&Form1Context));
            Form1Context.RegisterWg("vout_frm1_MetaLastLn",o);
          } // Fl_Value_Output* o
          o->end();
        } // Fl_Group* o
        Form1Context.tbs[0]=o;
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(30, 118, 790, 743, "Data");
        o->labelsize(18);
        o->hide();
        { clsSelectCols* o = new clsSelectCols(66, 255, 754, 590);
          o->box(FL_THIN_DOWN_FRAME);
          o->color(FL_BACKGROUND_COLOR);
          o->selection_color(FL_BACKGROUND_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(18);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->user_data((void*)(&Form1Context));
          o->align(Fl_Align(FL_ALIGN_TOP));
          o->when(FL_WHEN_RELEASE);
          Form1Context.RegisterWg("tbl_frm1_Data",o);
          o->end();
        } // clsSelectCols* o
        { Fl_Button* o = new Fl_Button(700, 130, 100, 25, "Next");
          o->callback((Fl_Callback*)cb_Next1, (void*)(&Form1Context));
          Form1Context.RegisterWg("btn_frm12Stat",o);
        } // Fl_Button* o
        { Fl_Button* o = new Fl_Button(701, 170, 100, 25, "Back");
          o->callback((Fl_Callback*)cb_Back, (void*)(&Form1Context));
          Form1Context.RegisterWg("btn_frm1B2F",o);
        } // Fl_Button* o
        { Fl_Choice* o = new Fl_Choice(426, 135, 160, 25, "Impedance:");
          o->down_box(FL_BORDER_BOX);
          o->labelsize(16);
          o->textsize(16);
          o->user_data((void*)(&Form1Context));
          Form1Context.RegisterWg("ch_ReIm_mode",o);
        } // Fl_Choice* o
        { Fl_Choice* o = new Fl_Choice(245, 135, 81, 25, "Frequency:");
          o->down_box(FL_BORDER_BOX);
          o->labelsize(16);
          o->textsize(16);
          o->user_data((void*)(&Form1Context));
          Form1Context.RegisterWg("ch_Frq_mode",o);
        } // Fl_Choice* o
        { Fl_Choice* o = new Fl_Choice(580, 210, 81, 25, "\317\206:");
          o->down_box(FL_BORDER_BOX);
          o->labelsize(16);
          o->textsize(16);
          o->user_data((void*)(&Form1Context));
          Form1Context.RegisterWg("ch_fi_mode",o);
        } // Fl_Choice* o
        { Fl_Choice* o = new Fl_Choice(580, 175, 81, 25, "Z:");
          o->down_box(FL_BORDER_BOX);
          o->labelsize(16);
          o->textsize(16);
          o->user_data((void*)(&Form1Context));
          Form1Context.RegisterWg("ch_Z_mode",o);
        } // Fl_Choice* o
        { Fl_Group* o = new Fl_Group(64, 183, 455, 51, "Columns");
          o->box(FL_GTK_DOWN_FRAME);
          { Fl_Value_Output* o = new Fl_Value_Output(140, 193, 75, 26, "Frq:");
            o->labelsize(16);
            o->textsize(16);
            o->user_data((void*)(&Form1Context));
            Form1Context.RegisterWg("vout_FrqIdx",o);
          } // Fl_Value_Output* o
          { Fl_Value_Output* o = new Fl_Value_Output(284, 193, 75, 26, "Z1:");
            o->labelsize(16);
            o->textsize(16);
            o->user_data((void*)(&Form1Context));
            Form1Context.RegisterWg("vout_ReIdx",o);
          } // Fl_Value_Output* o
          { Fl_Value_Output* o = new Fl_Value_Output(410, 193, 75, 26, "Z2:");
            o->labelsize(16);
            o->textsize(16);
            o->user_data((void*)(&Form1Context));
            Form1Context.RegisterWg("vout_ImIdx",o);
          } // Fl_Value_Output* o
          o->end();
        } // Fl_Group* o
        Form1Context.tbs[1]=o;
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(25, 114, 880, 747, "Preview");
        o->labelsize(18);
        { Fl_Button* o = new Fl_Button(710, 125, 100, 25, "Finish");
          o->callback((Fl_Callback*)cb_Finish, (void*)(&Form1Context));
          Form1Context.RegisterWg("btn_frm12Finish",o);
        } // Fl_Button* o
        { Fl_Button* o = new Fl_Button(585, 125, 100, 25, "Back");
          o->callback((Fl_Callback*)cb_Back1, (void*)(&Form1Context));
          Form1Context.RegisterWg("btn_frm1B2D",o);
        } // Fl_Button* o
        { Fl_Tabs* o = new Fl_Tabs(30, 195, 805, 630);
          o->labelsize(18);
          { Fl_Group* o = new Fl_Group(40, 230, 755, 595, "Table");
            o->labelsize(18);
            o->hide();
            { clsTblOutZ* o = new clsTblOutZ(75, 275, 470, 550, "Impedance Data");
              o->box(FL_THIN_DOWN_FRAME);
              o->color(FL_BACKGROUND_COLOR);
              o->selection_color(FL_BACKGROUND_COLOR);
              o->labeltype(FL_NORMAL_LABEL);
              o->labelfont(0);
              o->labelsize(18);
              o->labelcolor(FL_FOREGROUND_COLOR);
              o->user_data((void*)(&Form1Context));
              o->align(Fl_Align(FL_ALIGN_TOP));
              o->when(FL_WHEN_RELEASE);
              Form1Context.RegisterWg("tbl_frm1_TblOutZ",o);
              o->end();
            } // clsTblOutZ* o
            o->end();
          } // Fl_Group* o
          { Fl_Group* o = new Fl_Group(35, 240, 800, 580, "Nyquist");
            o->labelsize(18);
            { FL_PlotXY3_13::Fl_PlotXY3* o = new FL_PlotXY3_13::Fl_PlotXY3(75, 257, 750, 526);
              o->box(FL_GTK_DOWN_BOX);
              o->color(FL_BACKGROUND2_COLOR);
              o->selection_color(FL_BACKGROUND_COLOR);
              o->labeltype(FL_NORMAL_LABEL);
              o->labelfont(0);
              o->labelsize(14);
              o->labelcolor(FL_FOREGROUND_COLOR);
              o->user_data((void*)(&Form1Context));
              o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
              o->when(FL_WHEN_RELEASE);
              Form1Context.RegisterWg("pltxy3_main",o);
            } // FL_PlotXY3_13::Fl_PlotXY3* o
            { Fl_Rotated_Label* o = new Fl_Rotated_Label(35, 403, 35, 172);
              o->box(FL_NO_BOX);
              o->color(FL_LIGHT1);
              o->selection_color(FL_BACKGROUND_COLOR);
              o->labeltype(FL_NORMAL_LABEL);
              o->labelfont(0);
              o->labelsize(14);
              o->labelcolor(FL_FOREGROUND_COLOR);
              o->user_data((void*)(&Form1Context));
              o->align(Fl_Align(FL_ALIGN_CENTER));
              o->when(FL_WHEN_RELEASE);
              Form1Context.RegisterWg("rtl_Yax_inp",o);
              o->text("-Z.Im,Ω");
              o->angle(90);
            } // Fl_Rotated_Label* o
            { Fl_Output* o = new Fl_Output(400, 791, 150, 24);
              o->box(FL_NO_BOX);
              o->user_data((void*)(&Form1Context));
              Form1Context.RegisterWg("outx_Xlab_inp",o);
              o->value("Z.Re,Ω");
            } // Fl_Output* o
            o->end();
          } // Fl_Group* o
          o->end();
        } // Fl_Tabs* o
        Form1Context.tbs[2]=o;
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(30, 118, 795, 747, "Width");
        o->labelsize(18);
        o->hide();
        { Fl_Button* o = new Fl_Button(715, 125, 100, 25, "Next");
          o->callback((Fl_Callback*)cb_Next2, (void*)(&Form1Context));
        } // Fl_Button* o
        { Fl_Button* o = new Fl_Button(600, 125, 100, 25, "Back");
          o->callback((Fl_Callback*)cb_Back2, (void*)(&Form1Context));
        } // Fl_Button* o
        { clsCWBrowser* o = new clsCWBrowser(40, 235, 765, 500);
          o->box(FL_NO_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(14);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->textfont(4);
          o->user_data((void*)(&Form1Context));
          o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          o->when(FL_WHEN_RELEASE_ALWAYS);
          Form1Context.RegisterWg("brw_shw",o);
          o->has_scrollbar(clsCWBrowser::BOTH);
          o->type(FL_SELECT_BROWSER);
        } // clsCWBrowser* o
        Form1Context.tbs[3]=o;
        o->end();
      } // Fl_Group* o
      Form1Context.RegisterWg("tbs_frm1_map",o);
      o->end();
    } // Fl_Tabs* o
    { Fl_Group* o = new Fl_Group(495, 20, 130, 40, "Conversion schema file:");
      o->box(FL_GTK_DOWN_FRAME);
      o->labelsize(16);
      o->align(Fl_Align(FL_ALIGN_LEFT));
      { Fl_Button* o = new Fl_Button(505, 30, 40, 25, "@fileopen");
        o->labelcolor((Fl_Color)188);
        o->callback((Fl_Callback*)cb_fileopen, (void*)(&Form1Context));
        Form1Context.RegisterWg("btn_prfO",o);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(555, 30, 40, 25, "@filesave");
        o->labelcolor((Fl_Color)108);
        o->callback((Fl_Callback*)cb_filesave, (void*)(&Form1Context));
        Form1Context.RegisterWg("btn_prfS",o);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    Form1Context.Win(o);
    Form1Context.PrepWidgets();
    o->end();
  } // Fl_Double_Window* o
  return w;
}
